# Default values for IWO Kubernetes probe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#nameOverride: ""
#fullnameOverride: ""

# Replace the images with desired version
connectorImage:
  repository: intersight/pasadena
  tag: 1.0.9-1
  pullPolicy: IfNotPresent

collectorImage:
  repository: intersight/kubeturbo
  tag: 8.0.1
  pullPolicy: IfNotPresent

# IWO server major.minor version
iwoServerVersion: 8.0

# Target config -
# - If no targetConfig is specified, a default targetName will be created from the apiserver URL in the kubeconfig.
# - A probe with type Kubernetes-<targetName> will be registered, as well as your cluster will be added as a target
#   with the name Kubernetes-<targetName>.
#
#targetName: Cluster_Name

# Specify custom iwo-cluster-reader or iwo-cluster-admin role instead of the default cluster-admin role
roleName: "cluster-admin"

replicaCount: 2

# You can define what nodes should stay high-available based on the node role
# Master nodes are by default populated by --set HANodeConfig.nodeRoles="\"foo\"\,\"bar\""
HANodeConfig:
  nodeRoles: "\"master\""

# You can define how daemon pods are identified. Use either or both
# Note if you do not enable daemonPodDetectors, the default is to identify all pods running as kind = daemonSet
# Any entry for daemonPodDetectors would overwrite default. Recommend you do not use this parameter.
#daemonPodDetectors:
#   daemonPodNamespaces1: kube-system
#   daemonPodNamespaces2: OpenShift
#   daemonPodNamePatterns: .*ignorePod.*

args:
  # logging level
  logginglevel: 2
  # If running on k8s 1.10.x or older, set https to false and change port 10255 for kubelet
  kubelethttps: true
  kubeletport: 10250
  # set to false if using IP for stitching
  stitchuuid: true
  # if Kubernetes version is older than 1.6, then add another arg for move/resize action
  pre16k8sVersion: false

annotations:
  kubeturbo.io/controllable: "false"

resources: {}
